name: Tiam
favicon: null
layout_spectrum: 0.40299805952236056
typography_spectrum: 0.8628815948031843
title: tiam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#1d1d1d'
    - '#454545'
    - '#a3a3a3'
  brandStrength: 0.3125
  lightness: 0.23094844236038625
  saturation: 0.08890149206854403
  rhythmicContrast: 0.492162604117766
purpose: []
